services:
  #Dependencies injection activation
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Devsk\ContentElementRegistry\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Devsk\ContentElementRegistry\Listeners\ContentElementPreviewRenderer:
    tags:
      - name: event.listener
        identifier: 'contentElementPreviewRenderer'
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
