services:
  #Dependencies injection activation
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Devsk\ContentElementRegistry\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
